name: Lint GitHub Actions
on:
  push:
    paths: ['.github/**']
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 #v4.4.0
        with:
          show-progress: false
      - uses: alphagov/govuk-infrastructure/.github/actions/actionlint@main
